version: "3.9"

services:

  db:
    container_name: db
    image: "postgres:latest"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "caramelca"
    restart: unless-stopped
    ports:
      - "5432:5432"

  backend:
    depends_on:
      - db
    container_name: backend
    image: backend:latest
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/caramelca
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8888:8080"