version: "3.9"

services:

  db:
    container_name: db
    image: "postgres:latest"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    restart: unless-stopped
    ports:
      - "5432:5432"

  seq:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "50505:8080" #left - outer port, right - inner port
    environment:
      ACCEPT_EULA: "Y"
      SEQ_API_CANONICALURI: "http://localhost:50505"

  backend:
    depends_on:
      - db
      - seq
    container_name: backend
    image: backend:latest
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://db:5432/
      - DB_USER=postgres
      - DB_PWD=123456
    ports:
      - "8888:8080"